spring.datasource.url=jdbc:sqlite:bookmanager.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.sql.init.schema-locations=classpath:schema-sqlite.sql

spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.zaxxer.hikari=DEBUG