spring.datasource.url=jdbc:postgresql://localhost:5432/bookdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.schema-locations=classpath:schema-psql.sql
spring.datasource.username=bookuser
spring.datasource.password=testpassword