spring.application.name=BookManagementApp

spring.datasource.url=jdbc:postgresql://localhost:5432/bookdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialization=always
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.datasource.username=bookuser
spring.datasource.password=testpassword
