package com.twag.book_management_app.controller_tests;

import static org.hamcrest.Matchers.hasSize;
import static org.junit.Assert.assertEquals;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import com.twag.book_management_app.controller.BookController.EditRequest;
import com.twag.book_management_app.model.Book;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;

import java.util.ArrayList;
import java.util.List;

// SpringBootTest and AutoConfigureMockMvc provide application context, allow HTTP requests to endpoints.
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("dev")
@Testcontainers
public class BookControllerTest {
	@LocalServerPort
	private Integer port;

	// Run tests is a dedicated SQL container instead of having to create a more
	// difficult to manage
	// database using psql
	@Container
	@ServiceConnection
	static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

	@BeforeAll
	static void beforeAll() {
		postgres.start();
	}

	@AfterAll
	static void afterAll() {
		postgres.stop();
	}

	@DynamicPropertySource
	static void configureProperties(DynamicPropertyRegistry registry) {
		registry.add("spring.datasource.url", postgres::getJdbcUrl);
		registry.add("spring.datasource.username", postgres::getUsername);
		registry.add("spring.datasource.password", postgres::getPassword);
	}

	@BeforeEach
	void setup() {
		RestAssured.baseURI = "http://localhost:" + port;
	}

	/**
	 * Add books to database with POST so that tests can be performed on them.
	 * @param bookList Books to be added to database.
	 * @return List of IDs generated by the PostgreSQL database.
	 */
	ArrayList<Integer> loadBooksForTest(List<Book> bookList) {
		ArrayList<Integer> ids = new ArrayList<>();
		bookList.forEach(book -> ids.add(
				RestAssured.given()
						.contentType(ContentType.JSON)
						.body(book)
						.post("/api/books")
						.then()
						.statusCode(201)
						.extract()
						.as(Integer.class)));
		return ids;
	}

	@Autowired
	private JdbcTemplate jdbc;

	@BeforeEach
	void resetDatabase() {
		jdbc.execute("DELETE FROM all_books");
	}

	@Test
	public void testBookRetrieval() throws Exception {

		List<Book> bookList = List.of(
				new Book("Test Book", "lastname", "firstname", "Fantasy", 3),
				new Book("Test Two", "last", "first", "Fable", 1));

		loadBooksForTest(bookList);

		RestAssured.given()
				.contentType(ContentType.JSON)
				.when()
				.get("/api/books")
				.then()
				.statusCode(200)
				.body(".", hasSize(2));

		// TODO: test the sorted orders?
	}

	@Test
	public void testBookDeletion() throws Exception {
		List<Book> bookList = List.of(
				new Book("Test Book", "lastname", "firstname", "Fantasy", 3),
				new Book("Test Two", "last", "first", "Fable", 1));

		ArrayList<Integer> ids = loadBooksForTest(bookList);

		RestAssured.given()
				.contentType(ContentType.JSON)
				.when()
				.delete("/api/books/delete/{id}", ids.get(0));

		RestAssured.given()
				.get("/api/books")
				.then()
				.statusCode(200)
				.body(".", hasSize(1));
	}

	// TODO: Add the books and then update the test to simply pull the book and test the various updates instead of
	// repeatedly using the API unnecessarily
	@Test
	public void testBookUpdate() throws Exception {
		List<Book> bookList = List.of(
				new Book("Test Book", "lastname", "firstname", "Fantasy", 3),
				new Book("Test Two", "last", "first", "Fable", 1));

		// Insert book list and get IDs from the database for testing the book update
		ArrayList<Integer> ids = loadBooksForTest(bookList);

		// Test updating title
		final String newTitle = "Updated Title";
		RestAssured.given()
				.contentType(ContentType.JSON)
				.body(new EditRequest(newTitle))
				.when()
				.put("/api/books/updateTitle/{id}", ids.get(0))
				.then()
				.statusCode(200);

		// Get the book to test the title
		String titleToCheck = RestAssured.given()
				.contentType(ContentType.JSON)
				.get("/api/books/get/{id}", ids.get(0))
				.then()
				.statusCode(200)
				.extract()
				.path("title");
		assertEquals(newTitle, titleToCheck);

		// Test updating author last name
		final String newLastName = "UpdatedLastName";
		RestAssured.given()
				.contentType(ContentType.JSON)
				.body(new EditRequest(newLastName))
				.when()
				.put("/api/books/updateAuthorLast/{id}", ids.get(1))
				.then()
				.statusCode(200);

		String authorLastToCheck = RestAssured.given()
				.contentType(ContentType.JSON)
				.get("/api/books/get/{id}", ids.get(1))
				.then()
				.statusCode(200)
				.extract()
				.path("authorLast");
		assertEquals(newLastName, authorLastToCheck);

		final String newFirstName = "UpdatedFirstName";
		RestAssured.given()
				.contentType(ContentType.JSON)
				.body(new EditRequest(newFirstName))
				.when()
				.put("/api/books/updateAuthorFirst/{id}", ids.get(1))
				.then()
				.statusCode(200);

		String authorFirstToCheck = RestAssured.given()
				.contentType(ContentType.JSON)
				.get("/api/books/get/{id}", ids.get(1))
				.then()
				.statusCode(200)
				.extract()
				.path("authorFirst");
		assertEquals(newFirstName, authorFirstToCheck);

		final String newImagePath = "/test/path/to/img";
		RestAssured.given()
			.contentType(ContentType.JSON)
			.body(new EditRequest(newImagePath))
			.when()
			.put("/api/books/updateImagePath/{id}", ids.get(1))
			.then()
			.statusCode(200);
		
			String updatedPathCheck = RestAssured.given()
			.contentType(ContentType.JSON)
			.get("/api/books/get/{id}", ids.get(1))
			.then()
			.statusCode(200)
			.extract()
			.path("imagePath");
		assertEquals(newImagePath, updatedPathCheck);
	}
}
